{
//////////////////////////////////////////////////////////
//   This file has been automatically generated 
//     (Fri Jan  8 16:14:41 2016 by ROOT version5.34/32)
//   from TTree cbmsim//cbmroot
//   found on file: VetoSim_run=1.root
//////////////////////////////////////////////////////////


//Reset ROOT and connect tree file
   gROOT->Reset();
   TFile *f = (TFile*)gROOT->GetListOfFiles()->FindObject("VetoSim_run=1.root");
   if (!f) {
      f = new TFile("VetoSim_run=1.root");
   }
    f->GetObject("cbmsim",tree);

//Declaration of leaves types
   UInt_t          MCTrack_fUniqueID[952];
   UInt_t          MCTrack_fBits[952];
   Int_t           MCTrack_fPdgCode[952];
   Int_t           MCTrack_fMotherId[952];
   Double32_t      MCTrack_fPx[952];
   Double32_t      MCTrack_fPy[952];
   Double32_t      MCTrack_fPz[952];
   Double32_t      MCTrack_fStartX[952];
   Double32_t      MCTrack_fStartY[952];
   Double32_t      MCTrack_fStartZ[952];
   Double32_t      MCTrack_fStartT[952];
   Int_t           MCTrack_fNPoints[952];
   Double32_t      MCTrack_fMass[952];
   UInt_t          CaloCrystalHitSim_fUniqueID[3];
   UInt_t          CaloCrystalHitSim_fBits[3];
   set<FairLink>   CaloCrystalHitSim_fLinks[3];
   UInt_t          CaloCrystalHitSim_fEntryNr_fUniqueID[3];
   UInt_t          CaloCrystalHitSim_fEntryNr_fBits[3];
   Int_t           CaloCrystalHitSim_fEntryNr_fFile[3];
   Int_t           CaloCrystalHitSim_fEntryNr_fEntry[3];
   Int_t           CaloCrystalHitSim_fEntryNr_fType[3];
   Int_t           CaloCrystalHitSim_fEntryNr_fIndex[3];
   Float_t         CaloCrystalHitSim_fEntryNr_fWeight[3];
   Int_t           CaloCrystalHitSim_fDefaultType[3];
   Double32_t      CaloCrystalHitSim_fEnergy[3];
   Double32_t      CaloCrystalHitSim_fNf[3];
   Double32_t      CaloCrystalHitSim_fNs[3];
   Double32_t      CaloCrystalHitSim_fToT_Energy[3];
   ULong64_t       CaloCrystalHitSim_fTime[3];
   Int_t           CaloCrystalHitSim_fCrystalId[3];
   Int_t           CaloCrystalHitSim_fCrystalType[3];
   Int_t           CaloCrystalHitSim_fCrystalCopy[3];
   Int_t           CaloCrystalHitSim_fNSteps[3];
   Double32_t      CaloCrystalHitSim_fEinc[3];
   Int_t           CaloCrystalHitSim_fTrackID[3];
   Int_t           CaloCrystalHitSim_fVolumeID[3];
   Int_t           CaloCrystalHitSim_fParentTrackID[3];
   Int_t           CaloCrystalHitSim_fTrackPID[3];
   Int_t           CaloCrystalHitSim_fTrackUniqueID[3];
   UInt_t          STaRTraPoint_fUniqueID[18];
   UInt_t          STaRTraPoint_fBits[18];
   FairMultiLinkedData* STaRTraPoint_fLink[18];
   Int_t           STaRTraPoint_fTrackID[18];
   UInt_t          STaRTraPoint_fEventId[18];
   Double32_t      STaRTraPoint_fPx[18];
   Double32_t      STaRTraPoint_fPy[18];
   Double32_t      STaRTraPoint_fPz[18];
   Double32_t      STaRTraPoint_fTime[18];
   Double32_t      STaRTraPoint_fLength[18];
   Double32_t      STaRTraPoint_fELoss[18];
   Int_t           STaRTraPoint_fDetectorID[18];
   Double32_t      STaRTraPoint_fX[18];
   Double32_t      STaRTraPoint_fY[18];
   Double32_t      STaRTraPoint_fZ[18];
   Double32_t      STaRTraPoint_fX_out[18];
   Double32_t      STaRTraPoint_fY_out[18];
   Double32_t      STaRTraPoint_fZ_out[18];
   Double32_t      STaRTraPoint_fPx_out[18];
   Double32_t      STaRTraPoint_fPy_out[18];
   Double32_t      STaRTraPoint_fPz_out[18];
   Int_t           STaRTraPoint_fDetCopyID[18];
   UInt_t          DCHPoint_fUniqueID[1];
   UInt_t          DCHPoint_fBits[1];
   FairMultiLinkedData* DCHPoint_fLink[1];
   Int_t           DCHPoint_fTrackID[1];
   UInt_t          DCHPoint_fEventId[1];
   Double32_t      DCHPoint_fPx[1];
   Double32_t      DCHPoint_fPy[1];
   Double32_t      DCHPoint_fPz[1];
   Double32_t      DCHPoint_fTime[1];
   Double32_t      DCHPoint_fLength[1];
   Double32_t      DCHPoint_fELoss[1];
   Int_t           DCHPoint_fDetectorID[1];
   Double32_t      DCHPoint_fX[1];
   Double32_t      DCHPoint_fY[1];
   Double32_t      DCHPoint_fZ[1];
   Double32_t      DCHPoint_fX_out[1];
   Double32_t      DCHPoint_fY_out[1];
   Double32_t      DCHPoint_fZ_out[1];
   Double32_t      DCHPoint_fPx_out[1];
   Double32_t      DCHPoint_fPy_out[1];
   Double32_t      DCHPoint_fPz_out[1];
   Double32_t      DCHPoint_fLocalX_in[1];
   Double32_t      DCHPoint_fLocalY_in[1];
   Double32_t      DCHPoint_fLocalZ_in[1];
   Double32_t      DCHPoint_fLocalPx_in[1];
   Double32_t      DCHPoint_fLocalPy_in[1];
   Double32_t      DCHPoint_fLocalPz_in[1];
   Double32_t      DCHPoint_fLocalX_out[1];
   Double32_t      DCHPoint_fLocalY_out[1];
   Double32_t      DCHPoint_fLocalZ_out[1];
   Double32_t      DCHPoint_fLocalPx_out[1];
   Double32_t      DCHPoint_fLocalPy_out[1];
   Double32_t      DCHPoint_fLocalPz_out[1];
   Int_t           DCHPoint_fModule[1];
   Int_t           DCHPoint_fLayer[1];
   Int_t           DCHPoint_fCell[1];
   UInt_t          TOFPoint_fUniqueID[0];
   UInt_t          TOFPoint_fBits[0];
   FairMultiLinkedData* TOFPoint_fLink[0];
   Int_t           TOFPoint_fTrackID[0];
   UInt_t          TOFPoint_fEventId[0];
   Double32_t      TOFPoint_fPx[0];
   Double32_t      TOFPoint_fPy[0];
   Double32_t      TOFPoint_fPz[0];
   Double32_t      TOFPoint_fTime[0];
   Double32_t      TOFPoint_fLength[0];
   Double32_t      TOFPoint_fELoss[0];
   Int_t           TOFPoint_fDetectorID[0];
   Double32_t      TOFPoint_fX[0];
   Double32_t      TOFPoint_fY[0];
   Double32_t      TOFPoint_fZ[0];
   Double32_t      TOFPoint_fX_out[0];
   Double32_t      TOFPoint_fY_out[0];
   Double32_t      TOFPoint_fZ_out[0];
   Double32_t      TOFPoint_fPx_out[0];
   Double32_t      TOFPoint_fPy_out[0];
   Double32_t      TOFPoint_fPz_out[0];
   UInt_t          mTOFPoint_fUniqueID[1];
   UInt_t          mTOFPoint_fBits[1];
   FairMultiLinkedData* mTOFPoint_fLink[1];
   Int_t           mTOFPoint_fTrackID[1];
   UInt_t          mTOFPoint_fEventId[1];
   Double32_t      mTOFPoint_fPx[1];
   Double32_t      mTOFPoint_fPy[1];
   Double32_t      mTOFPoint_fPz[1];
   Double32_t      mTOFPoint_fTime[1];
   Double32_t      mTOFPoint_fLength[1];
   Double32_t      mTOFPoint_fELoss[1];
   Int_t           mTOFPoint_fDetectorID[1];
   Double32_t      mTOFPoint_fX[1];
   Double32_t      mTOFPoint_fY[1];
   Double32_t      mTOFPoint_fZ[1];
   Double32_t      mTOFPoint_fX_out[1];
   Double32_t      mTOFPoint_fY_out[1];
   Double32_t      mTOFPoint_fZ_out[1];
   Double32_t      mTOFPoint_fPx_out[1];
   Double32_t      mTOFPoint_fPy_out[1];
   Double32_t      mTOFPoint_fPz_out[1];
   UInt_t          LandPoint_fUniqueID[638];
   UInt_t          LandPoint_fBits[638];
   FairMultiLinkedData* LandPoint_fLink[638];
   Int_t           LandPoint_fTrackID[638];
   UInt_t          LandPoint_fEventId[638];
   Double32_t      LandPoint_fPx[638];
   Double32_t      LandPoint_fPy[638];
   Double32_t      LandPoint_fPz[638];
   Double32_t      LandPoint_fTime[638];
   Double32_t      LandPoint_fLength[638];
   Double32_t      LandPoint_fELoss[638];
   Int_t           LandPoint_fDetectorID[638];
   Double32_t      LandPoint_fX[638];
   Double32_t      LandPoint_fY[638];
   Double32_t      LandPoint_fZ[638];
   Double32_t      LandPoint_fX_out[638];
   Double32_t      LandPoint_fY_out[638];
   Double32_t      LandPoint_fZ_out[638];
   Double32_t      LandPoint_fPx_out[638];
   Double32_t      LandPoint_fPy_out[638];
   Double32_t      LandPoint_fPz_out[638];
   Int_t           LandPoint_fSector[638];
   Int_t           LandPoint_fPaddleNb[638];
   Int_t           LandPoint_fPaddleTyp[638];
   Double_t        LandPoint_fLightYield[638];
   UInt_t          LandFirstHits_fUniqueID[1];
   UInt_t          LandFirstHits_fBits[1];
   Double32_t      LandFirstHits_fx0[1];
   Double32_t      LandFirstHits_fy0[1];
   Double32_t      LandFirstHits_fz0[1];
   Double32_t      LandFirstHits_fT0[1];
   Double32_t      LandFirstHits_fx1[1];
   Double32_t      LandFirstHits_fy1[1];
   Double32_t      LandFirstHits_fz1[1];
   Double32_t      LandFirstHits_fT1[1];
   Double32_t      LandFirstHits_fx2[1];
   Double32_t      LandFirstHits_fy2[1];
   Double32_t      LandFirstHits_fz2[1];
   Double32_t      LandFirstHits_fT2[1];
   Double32_t      LandFirstHits_fx3[1];
   Double32_t      LandFirstHits_fy3[1];
   Double32_t      LandFirstHits_fz3[1];
   Double32_t      LandFirstHits_fT3[1];
   Double32_t      LandFirstHits_fx4[1];
   Double32_t      LandFirstHits_fy4[1];
   Double32_t      LandFirstHits_fz4[1];
   Double32_t      LandFirstHits_fT4[1];
   Double32_t      LandFirstHits_fx5[1];
   Double32_t      LandFirstHits_fy5[1];
   Double32_t      LandFirstHits_fz5[1];
   Double32_t      LandFirstHits_fT5[1];
   UInt_t          veto_segPoint_fUniqueID[17];
   UInt_t          veto_segPoint_fBits[17];
   FairMultiLinkedData* veto_segPoint_fLink[17];
   Int_t           veto_segPoint_fTrackID[17];
   UInt_t          veto_segPoint_fEventId[17];
   Double32_t      veto_segPoint_fPx[17];
   Double32_t      veto_segPoint_fPy[17];
   Double32_t      veto_segPoint_fPz[17];
   Double32_t      veto_segPoint_fTime[17];
   Double32_t      veto_segPoint_fLength[17];
   Double32_t      veto_segPoint_fELoss[17];
   Int_t           veto_segPoint_fDetectorID[17];
   Double32_t      veto_segPoint_fX[17];
   Double32_t      veto_segPoint_fY[17];
   Double32_t      veto_segPoint_fZ[17];
   Double32_t      veto_segPoint_fX_out[17];
   Double32_t      veto_segPoint_fY_out[17];
   Double32_t      veto_segPoint_fZ_out[17];
   Double32_t      veto_segPoint_fPx_out[17];
   Double32_t      veto_segPoint_fPy_out[17];
   Double32_t      veto_segPoint_fPz_out[17];
   Int_t           veto_segPoint_fSector[17];
   Int_t           veto_segPoint_fPaddleNb[17];
   Int_t           veto_segPoint_fPaddleTyp[17];
   Double_t        veto_segPoint_fLightYield[17];
   UInt_t          veto_segFirstHits_fUniqueID[1];
   UInt_t          veto_segFirstHits_fBits[1];
   Double32_t      veto_segFirstHits_fx0[1];
   Double32_t      veto_segFirstHits_fy0[1];
   Double32_t      veto_segFirstHits_fz0[1];
   Double32_t      veto_segFirstHits_fT0[1];
   Double32_t      veto_segFirstHits_fx1[1];
   Double32_t      veto_segFirstHits_fy1[1];
   Double32_t      veto_segFirstHits_fz1[1];
   Double32_t      veto_segFirstHits_fT1[1];
   Double32_t      veto_segFirstHits_fx2[1];
   Double32_t      veto_segFirstHits_fy2[1];
   Double32_t      veto_segFirstHits_fz2[1];
   Double32_t      veto_segFirstHits_fT2[1];
   Double32_t      veto_segFirstHits_fx3[1];
   Double32_t      veto_segFirstHits_fy3[1];
   Double32_t      veto_segFirstHits_fz3[1];
   Double32_t      veto_segFirstHits_fT3[1];
   Double32_t      veto_segFirstHits_fx4[1];
   Double32_t      veto_segFirstHits_fy4[1];
   Double32_t      veto_segFirstHits_fz4[1];
   Double32_t      veto_segFirstHits_fT4[1];
   Double32_t      veto_segFirstHits_fx5[1];
   Double32_t      veto_segFirstHits_fy5[1];
   Double32_t      veto_segFirstHits_fz5[1];
   Double32_t      veto_segFirstHits_fT5[1];
   UInt_t          MFIPoint_fUniqueID[0];
   UInt_t          MFIPoint_fBits[0];
   FairMultiLinkedData* MFIPoint_fLink[0];
   Int_t           MFIPoint_fTrackID[0];
   UInt_t          MFIPoint_fEventId[0];
   Double32_t      MFIPoint_fPx[0];
   Double32_t      MFIPoint_fPy[0];
   Double32_t      MFIPoint_fPz[0];
   Double32_t      MFIPoint_fTime[0];
   Double32_t      MFIPoint_fLength[0];
   Double32_t      MFIPoint_fELoss[0];
   Int_t           MFIPoint_fDetectorID[0];
   Double32_t      MFIPoint_fX[0];
   Double32_t      MFIPoint_fY[0];
   Double32_t      MFIPoint_fZ[0];
   Double32_t      MFIPoint_fX_out[0];
   Double32_t      MFIPoint_fY_out[0];
   Double32_t      MFIPoint_fZ_out[0];
   Double32_t      MFIPoint_fPx_out[0];
   Double32_t      MFIPoint_fPy_out[0];
   Double32_t      MFIPoint_fPz_out[0];
   Int_t           MFIPoint_fModule[0];
   UInt_t          PSPPoint_fUniqueID[114];
   UInt_t          PSPPoint_fBits[114];
   FairMultiLinkedData* PSPPoint_fLink[114];
   Int_t           PSPPoint_fTrackID[114];
   UInt_t          PSPPoint_fEventId[114];
   Double32_t      PSPPoint_fPx[114];
   Double32_t      PSPPoint_fPy[114];
   Double32_t      PSPPoint_fPz[114];
   Double32_t      PSPPoint_fTime[114];
   Double32_t      PSPPoint_fLength[114];
   Double32_t      PSPPoint_fELoss[114];
   Int_t           PSPPoint_fDetectorID[114];
   Double32_t      PSPPoint_fX[114];
   Double32_t      PSPPoint_fY[114];
   Double32_t      PSPPoint_fZ[114];
   Double32_t      PSPPoint_fX_out[114];
   Double32_t      PSPPoint_fY_out[114];
   Double32_t      PSPPoint_fZ_out[114];
   Double32_t      PSPPoint_fPx_out[114];
   Double32_t      PSPPoint_fPy_out[114];
   Double32_t      PSPPoint_fPz_out[114];
   Int_t           PSPPoint_fModule[114];
   UInt_t          cbmroot_Event_MCEventHeader_TNamed_fUniqueID;
   UInt_t          cbmroot_Event_MCEventHeader_TNamed_fBits;
   TString         cbmroot_Event_MCEventHeader_TNamed_fName;
   TString         cbmroot_Event_MCEventHeader_TNamed_fTitle;
   UInt_t          cbmroot_Event_MCEventHeader_fRunId;
   UInt_t          cbmroot_Event_MCEventHeader_fEventId;
   Double32_t      cbmroot_Event_MCEventHeader_fX;
   Double32_t      cbmroot_Event_MCEventHeader_fY;
   Double32_t      cbmroot_Event_MCEventHeader_fZ;
   Double32_t      cbmroot_Event_MCEventHeader_fT;
   Double32_t      cbmroot_Event_MCEventHeader_fB;
   Int_t           cbmroot_Event_MCEventHeader_fNPrim;
   Bool_t          cbmroot_Event_MCEventHeader_fIsSet;
   Double32_t      cbmroot_Event_MCEventHeader_fRotX;
   Double32_t      cbmroot_Event_MCEventHeader_fRotY;
   Double32_t      cbmroot_Event_MCEventHeader_fRotZ;
   UInt_t          GeoTracks_fUniqueID[1494];
   UInt_t          GeoTracks_fBits[1494];
   UInt_t          GeoTracks_fGeoAtt[1494];
   Short_t         GeoTracks_fLineColor[1494];
   Short_t         GeoTracks_fLineStyle[1494];
   Short_t         GeoTracks_fLineWidth[1494];
   Short_t         GeoTracks_fMarkerColor[1494];
   Short_t         GeoTracks_fMarkerStyle[1494];
   Float_t         GeoTracks_fMarkerSize[1494];
   Int_t           GeoTracks_fPDG[1494];
   Int_t           GeoTracks_fId[1494];
   TVirtualGeoTrack* GeoTracks_fParent[1494];
   TObject*        GeoTracks_fParticle[1494];
   TObjArray*      GeoTracks_fTracks[1494];
   Int_t           GeoTracks_fPointsSize[1494];
   Int_t           GeoTracks_fNpoints[1494];
   Double_t        GeoTracks_fPoints[1494];

   // Set branch addresses.
   cbmsim->SetBranchAddress("MCTrack",&cbmroot_Stack_MCTrack_);
   cbmsim->SetBranchAddress("MCTrack.fUniqueID",MCTrack_fUniqueID);
   cbmsim->SetBranchAddress("MCTrack.fBits",MCTrack_fBits);
   cbmsim->SetBranchAddress("MCTrack.fPdgCode",MCTrack_fPdgCode);
   cbmsim->SetBranchAddress("MCTrack.fMotherId",MCTrack_fMotherId);
   cbmsim->SetBranchAddress("MCTrack.fPx",MCTrack_fPx);
   cbmsim->SetBranchAddress("MCTrack.fPy",MCTrack_fPy);
   cbmsim->SetBranchAddress("MCTrack.fPz",MCTrack_fPz);
   cbmsim->SetBranchAddress("MCTrack.fStartX",MCTrack_fStartX);
   cbmsim->SetBranchAddress("MCTrack.fStartY",MCTrack_fStartY);
   cbmsim->SetBranchAddress("MCTrack.fStartZ",MCTrack_fStartZ);
   cbmsim->SetBranchAddress("MCTrack.fStartT",MCTrack_fStartT);
   cbmsim->SetBranchAddress("MCTrack.fNPoints",MCTrack_fNPoints);
   cbmsim->SetBranchAddress("MCTrack.fMass",MCTrack_fMass);
   cbmsim->SetBranchAddress("CaloCrystalHitSim",&cbmroot_Califa_CaloCrystalHitSim_);
   cbmsim->SetBranchAddress("CaloCrystalHitSim.fUniqueID",CaloCrystalHitSim_fUniqueID);
   cbmsim->SetBranchAddress("CaloCrystalHitSim.fBits",CaloCrystalHitSim_fBits);
   cbmsim->SetBranchAddress("CaloCrystalHitSim.fLinks",CaloCrystalHitSim_fLinks);
   cbmsim->SetBranchAddress("CaloCrystalHitSim.fEntryNr.fUniqueID",CaloCrystalHitSim_fEntryNr_fUniqueID);
   cbmsim->SetBranchAddress("CaloCrystalHitSim.fEntryNr.fBits",CaloCrystalHitSim_fEntryNr_fBits);
   cbmsim->SetBranchAddress("CaloCrystalHitSim.fEntryNr.fFile",CaloCrystalHitSim_fEntryNr_fFile);
   cbmsim->SetBranchAddress("CaloCrystalHitSim.fEntryNr.fEntry",CaloCrystalHitSim_fEntryNr_fEntry);
   cbmsim->SetBranchAddress("CaloCrystalHitSim.fEntryNr.fType",CaloCrystalHitSim_fEntryNr_fType);
   cbmsim->SetBranchAddress("CaloCrystalHitSim.fEntryNr.fIndex",CaloCrystalHitSim_fEntryNr_fIndex);
   cbmsim->SetBranchAddress("CaloCrystalHitSim.fEntryNr.fWeight",CaloCrystalHitSim_fEntryNr_fWeight);
   cbmsim->SetBranchAddress("CaloCrystalHitSim.fDefaultType",CaloCrystalHitSim_fDefaultType);
   cbmsim->SetBranchAddress("CaloCrystalHitSim.fEnergy",CaloCrystalHitSim_fEnergy);
   cbmsim->SetBranchAddress("CaloCrystalHitSim.fNf",CaloCrystalHitSim_fNf);
   cbmsim->SetBranchAddress("CaloCrystalHitSim.fNs",CaloCrystalHitSim_fNs);
   cbmsim->SetBranchAddress("CaloCrystalHitSim.fToT_Energy",CaloCrystalHitSim_fToT_Energy);
   cbmsim->SetBranchAddress("CaloCrystalHitSim.fTime",CaloCrystalHitSim_fTime);
   cbmsim->SetBranchAddress("CaloCrystalHitSim.fCrystalId",CaloCrystalHitSim_fCrystalId);
   cbmsim->SetBranchAddress("CaloCrystalHitSim.fCrystalType",CaloCrystalHitSim_fCrystalType);
   cbmsim->SetBranchAddress("CaloCrystalHitSim.fCrystalCopy",CaloCrystalHitSim_fCrystalCopy);
   cbmsim->SetBranchAddress("CaloCrystalHitSim.fNSteps",CaloCrystalHitSim_fNSteps);
   cbmsim->SetBranchAddress("CaloCrystalHitSim.fEinc",CaloCrystalHitSim_fEinc);
   cbmsim->SetBranchAddress("CaloCrystalHitSim.fTrackID",CaloCrystalHitSim_fTrackID);
   cbmsim->SetBranchAddress("CaloCrystalHitSim.fVolumeID",CaloCrystalHitSim_fVolumeID);
   cbmsim->SetBranchAddress("CaloCrystalHitSim.fParentTrackID",CaloCrystalHitSim_fParentTrackID);
   cbmsim->SetBranchAddress("CaloCrystalHitSim.fTrackPID",CaloCrystalHitSim_fTrackPID);
   cbmsim->SetBranchAddress("CaloCrystalHitSim.fTrackUniqueID",CaloCrystalHitSim_fTrackUniqueID);
   cbmsim->SetBranchAddress("STaRTraPoint",&cbmroot_STaRTrack_STaRTraPoint_);
   cbmsim->SetBranchAddress("STaRTraPoint.fUniqueID",STaRTraPoint_fUniqueID);
   cbmsim->SetBranchAddress("STaRTraPoint.fBits",STaRTraPoint_fBits);
   cbmsim->SetBranchAddress("STaRTraPoint.fLink",STaRTraPoint_fLink);
   cbmsim->SetBranchAddress("STaRTraPoint.fTrackID",STaRTraPoint_fTrackID);
   cbmsim->SetBranchAddress("STaRTraPoint.fEventId",STaRTraPoint_fEventId);
   cbmsim->SetBranchAddress("STaRTraPoint.fPx",STaRTraPoint_fPx);
   cbmsim->SetBranchAddress("STaRTraPoint.fPy",STaRTraPoint_fPy);
   cbmsim->SetBranchAddress("STaRTraPoint.fPz",STaRTraPoint_fPz);
   cbmsim->SetBranchAddress("STaRTraPoint.fTime",STaRTraPoint_fTime);
   cbmsim->SetBranchAddress("STaRTraPoint.fLength",STaRTraPoint_fLength);
   cbmsim->SetBranchAddress("STaRTraPoint.fELoss",STaRTraPoint_fELoss);
   cbmsim->SetBranchAddress("STaRTraPoint.fDetectorID",STaRTraPoint_fDetectorID);
   cbmsim->SetBranchAddress("STaRTraPoint.fX",STaRTraPoint_fX);
   cbmsim->SetBranchAddress("STaRTraPoint.fY",STaRTraPoint_fY);
   cbmsim->SetBranchAddress("STaRTraPoint.fZ",STaRTraPoint_fZ);
   cbmsim->SetBranchAddress("STaRTraPoint.fX_out",STaRTraPoint_fX_out);
   cbmsim->SetBranchAddress("STaRTraPoint.fY_out",STaRTraPoint_fY_out);
   cbmsim->SetBranchAddress("STaRTraPoint.fZ_out",STaRTraPoint_fZ_out);
   cbmsim->SetBranchAddress("STaRTraPoint.fPx_out",STaRTraPoint_fPx_out);
   cbmsim->SetBranchAddress("STaRTraPoint.fPy_out",STaRTraPoint_fPy_out);
   cbmsim->SetBranchAddress("STaRTraPoint.fPz_out",STaRTraPoint_fPz_out);
   cbmsim->SetBranchAddress("STaRTraPoint.fDetCopyID",STaRTraPoint_fDetCopyID);
   cbmsim->SetBranchAddress("DCHPoint",&cbmroot_Dch_DCHPoint_);
   cbmsim->SetBranchAddress("DCHPoint.fUniqueID",DCHPoint_fUniqueID);
   cbmsim->SetBranchAddress("DCHPoint.fBits",DCHPoint_fBits);
   cbmsim->SetBranchAddress("DCHPoint.fLink",DCHPoint_fLink);
   cbmsim->SetBranchAddress("DCHPoint.fTrackID",DCHPoint_fTrackID);
   cbmsim->SetBranchAddress("DCHPoint.fEventId",DCHPoint_fEventId);
   cbmsim->SetBranchAddress("DCHPoint.fPx",DCHPoint_fPx);
   cbmsim->SetBranchAddress("DCHPoint.fPy",DCHPoint_fPy);
   cbmsim->SetBranchAddress("DCHPoint.fPz",DCHPoint_fPz);
   cbmsim->SetBranchAddress("DCHPoint.fTime",DCHPoint_fTime);
   cbmsim->SetBranchAddress("DCHPoint.fLength",DCHPoint_fLength);
   cbmsim->SetBranchAddress("DCHPoint.fELoss",DCHPoint_fELoss);
   cbmsim->SetBranchAddress("DCHPoint.fDetectorID",DCHPoint_fDetectorID);
   cbmsim->SetBranchAddress("DCHPoint.fX",DCHPoint_fX);
   cbmsim->SetBranchAddress("DCHPoint.fY",DCHPoint_fY);
   cbmsim->SetBranchAddress("DCHPoint.fZ",DCHPoint_fZ);
   cbmsim->SetBranchAddress("DCHPoint.fX_out",DCHPoint_fX_out);
   cbmsim->SetBranchAddress("DCHPoint.fY_out",DCHPoint_fY_out);
   cbmsim->SetBranchAddress("DCHPoint.fZ_out",DCHPoint_fZ_out);
   cbmsim->SetBranchAddress("DCHPoint.fPx_out",DCHPoint_fPx_out);
   cbmsim->SetBranchAddress("DCHPoint.fPy_out",DCHPoint_fPy_out);
   cbmsim->SetBranchAddress("DCHPoint.fPz_out",DCHPoint_fPz_out);
   cbmsim->SetBranchAddress("DCHPoint.fLocalX_in",DCHPoint_fLocalX_in);
   cbmsim->SetBranchAddress("DCHPoint.fLocalY_in",DCHPoint_fLocalY_in);
   cbmsim->SetBranchAddress("DCHPoint.fLocalZ_in",DCHPoint_fLocalZ_in);
   cbmsim->SetBranchAddress("DCHPoint.fLocalPx_in",DCHPoint_fLocalPx_in);
   cbmsim->SetBranchAddress("DCHPoint.fLocalPy_in",DCHPoint_fLocalPy_in);
   cbmsim->SetBranchAddress("DCHPoint.fLocalPz_in",DCHPoint_fLocalPz_in);
   cbmsim->SetBranchAddress("DCHPoint.fLocalX_out",DCHPoint_fLocalX_out);
   cbmsim->SetBranchAddress("DCHPoint.fLocalY_out",DCHPoint_fLocalY_out);
   cbmsim->SetBranchAddress("DCHPoint.fLocalZ_out",DCHPoint_fLocalZ_out);
   cbmsim->SetBranchAddress("DCHPoint.fLocalPx_out",DCHPoint_fLocalPx_out);
   cbmsim->SetBranchAddress("DCHPoint.fLocalPy_out",DCHPoint_fLocalPy_out);
   cbmsim->SetBranchAddress("DCHPoint.fLocalPz_out",DCHPoint_fLocalPz_out);
   cbmsim->SetBranchAddress("DCHPoint.fModule",DCHPoint_fModule);
   cbmsim->SetBranchAddress("DCHPoint.fLayer",DCHPoint_fLayer);
   cbmsim->SetBranchAddress("DCHPoint.fCell",DCHPoint_fCell);
   cbmsim->SetBranchAddress("TOFPoint",&cbmroot_Tof_TOFPoint_);
   cbmsim->SetBranchAddress("TOFPoint.fUniqueID",&TOFPoint_fUniqueID);
   cbmsim->SetBranchAddress("TOFPoint.fBits",&TOFPoint_fBits);
   cbmsim->SetBranchAddress("TOFPoint.fLink",&TOFPoint_fLink);
   cbmsim->SetBranchAddress("TOFPoint.fTrackID",&TOFPoint_fTrackID);
   cbmsim->SetBranchAddress("TOFPoint.fEventId",&TOFPoint_fEventId);
   cbmsim->SetBranchAddress("TOFPoint.fPx",&TOFPoint_fPx);
   cbmsim->SetBranchAddress("TOFPoint.fPy",&TOFPoint_fPy);
   cbmsim->SetBranchAddress("TOFPoint.fPz",&TOFPoint_fPz);
   cbmsim->SetBranchAddress("TOFPoint.fTime",&TOFPoint_fTime);
   cbmsim->SetBranchAddress("TOFPoint.fLength",&TOFPoint_fLength);
   cbmsim->SetBranchAddress("TOFPoint.fELoss",&TOFPoint_fELoss);
   cbmsim->SetBranchAddress("TOFPoint.fDetectorID",&TOFPoint_fDetectorID);
   cbmsim->SetBranchAddress("TOFPoint.fX",&TOFPoint_fX);
   cbmsim->SetBranchAddress("TOFPoint.fY",&TOFPoint_fY);
   cbmsim->SetBranchAddress("TOFPoint.fZ",&TOFPoint_fZ);
   cbmsim->SetBranchAddress("TOFPoint.fX_out",&TOFPoint_fX_out);
   cbmsim->SetBranchAddress("TOFPoint.fY_out",&TOFPoint_fY_out);
   cbmsim->SetBranchAddress("TOFPoint.fZ_out",&TOFPoint_fZ_out);
   cbmsim->SetBranchAddress("TOFPoint.fPx_out",&TOFPoint_fPx_out);
   cbmsim->SetBranchAddress("TOFPoint.fPy_out",&TOFPoint_fPy_out);
   cbmsim->SetBranchAddress("TOFPoint.fPz_out",&TOFPoint_fPz_out);
   cbmsim->SetBranchAddress("mTOFPoint",&cbmroot_mTof_mTOFPoint_);
   cbmsim->SetBranchAddress("mTOFPoint.fUniqueID",mTOFPoint_fUniqueID);
   cbmsim->SetBranchAddress("mTOFPoint.fBits",mTOFPoint_fBits);
   cbmsim->SetBranchAddress("mTOFPoint.fLink",mTOFPoint_fLink);
   cbmsim->SetBranchAddress("mTOFPoint.fTrackID",mTOFPoint_fTrackID);
   cbmsim->SetBranchAddress("mTOFPoint.fEventId",mTOFPoint_fEventId);
   cbmsim->SetBranchAddress("mTOFPoint.fPx",mTOFPoint_fPx);
   cbmsim->SetBranchAddress("mTOFPoint.fPy",mTOFPoint_fPy);
   cbmsim->SetBranchAddress("mTOFPoint.fPz",mTOFPoint_fPz);
   cbmsim->SetBranchAddress("mTOFPoint.fTime",mTOFPoint_fTime);
   cbmsim->SetBranchAddress("mTOFPoint.fLength",mTOFPoint_fLength);
   cbmsim->SetBranchAddress("mTOFPoint.fELoss",mTOFPoint_fELoss);
   cbmsim->SetBranchAddress("mTOFPoint.fDetectorID",mTOFPoint_fDetectorID);
   cbmsim->SetBranchAddress("mTOFPoint.fX",mTOFPoint_fX);
   cbmsim->SetBranchAddress("mTOFPoint.fY",mTOFPoint_fY);
   cbmsim->SetBranchAddress("mTOFPoint.fZ",mTOFPoint_fZ);
   cbmsim->SetBranchAddress("mTOFPoint.fX_out",mTOFPoint_fX_out);
   cbmsim->SetBranchAddress("mTOFPoint.fY_out",mTOFPoint_fY_out);
   cbmsim->SetBranchAddress("mTOFPoint.fZ_out",mTOFPoint_fZ_out);
   cbmsim->SetBranchAddress("mTOFPoint.fPx_out",mTOFPoint_fPx_out);
   cbmsim->SetBranchAddress("mTOFPoint.fPy_out",mTOFPoint_fPy_out);
   cbmsim->SetBranchAddress("mTOFPoint.fPz_out",mTOFPoint_fPz_out);
   cbmsim->SetBranchAddress("LandPoint",&cbmroot_Land_LandPoint_);
   cbmsim->SetBranchAddress("LandPoint.fUniqueID",LandPoint_fUniqueID);
   cbmsim->SetBranchAddress("LandPoint.fBits",LandPoint_fBits);
   cbmsim->SetBranchAddress("LandPoint.fLink",LandPoint_fLink);
   cbmsim->SetBranchAddress("LandPoint.fTrackID",LandPoint_fTrackID);
   cbmsim->SetBranchAddress("LandPoint.fEventId",LandPoint_fEventId);
   cbmsim->SetBranchAddress("LandPoint.fPx",LandPoint_fPx);
   cbmsim->SetBranchAddress("LandPoint.fPy",LandPoint_fPy);
   cbmsim->SetBranchAddress("LandPoint.fPz",LandPoint_fPz);
   cbmsim->SetBranchAddress("LandPoint.fTime",LandPoint_fTime);
   cbmsim->SetBranchAddress("LandPoint.fLength",LandPoint_fLength);
   cbmsim->SetBranchAddress("LandPoint.fELoss",LandPoint_fELoss);
   cbmsim->SetBranchAddress("LandPoint.fDetectorID",LandPoint_fDetectorID);
   cbmsim->SetBranchAddress("LandPoint.fX",LandPoint_fX);
   cbmsim->SetBranchAddress("LandPoint.fY",LandPoint_fY);
   cbmsim->SetBranchAddress("LandPoint.fZ",LandPoint_fZ);
   cbmsim->SetBranchAddress("LandPoint.fX_out",LandPoint_fX_out);
   cbmsim->SetBranchAddress("LandPoint.fY_out",LandPoint_fY_out);
   cbmsim->SetBranchAddress("LandPoint.fZ_out",LandPoint_fZ_out);
   cbmsim->SetBranchAddress("LandPoint.fPx_out",LandPoint_fPx_out);
   cbmsim->SetBranchAddress("LandPoint.fPy_out",LandPoint_fPy_out);
   cbmsim->SetBranchAddress("LandPoint.fPz_out",LandPoint_fPz_out);
   cbmsim->SetBranchAddress("LandPoint.fSector",LandPoint_fSector);
   cbmsim->SetBranchAddress("LandPoint.fPaddleNb",LandPoint_fPaddleNb);
   cbmsim->SetBranchAddress("LandPoint.fPaddleTyp",LandPoint_fPaddleTyp);
   cbmsim->SetBranchAddress("LandPoint.fLightYield",LandPoint_fLightYield);
   cbmsim->SetBranchAddress("LandFirstHits",&cbmroot_Land_LandFirstHits_);
   cbmsim->SetBranchAddress("LandFirstHits.fUniqueID",LandFirstHits_fUniqueID);
   cbmsim->SetBranchAddress("LandFirstHits.fBits",LandFirstHits_fBits);
   cbmsim->SetBranchAddress("LandFirstHits.fx0",LandFirstHits_fx0);
   cbmsim->SetBranchAddress("LandFirstHits.fy0",LandFirstHits_fy0);
   cbmsim->SetBranchAddress("LandFirstHits.fz0",LandFirstHits_fz0);
   cbmsim->SetBranchAddress("LandFirstHits.fT0",LandFirstHits_fT0);
   cbmsim->SetBranchAddress("LandFirstHits.fx1",LandFirstHits_fx1);
   cbmsim->SetBranchAddress("LandFirstHits.fy1",LandFirstHits_fy1);
   cbmsim->SetBranchAddress("LandFirstHits.fz1",LandFirstHits_fz1);
   cbmsim->SetBranchAddress("LandFirstHits.fT1",LandFirstHits_fT1);
   cbmsim->SetBranchAddress("LandFirstHits.fx2",LandFirstHits_fx2);
   cbmsim->SetBranchAddress("LandFirstHits.fy2",LandFirstHits_fy2);
   cbmsim->SetBranchAddress("LandFirstHits.fz2",LandFirstHits_fz2);
   cbmsim->SetBranchAddress("LandFirstHits.fT2",LandFirstHits_fT2);
   cbmsim->SetBranchAddress("LandFirstHits.fx3",LandFirstHits_fx3);
   cbmsim->SetBranchAddress("LandFirstHits.fy3",LandFirstHits_fy3);
   cbmsim->SetBranchAddress("LandFirstHits.fz3",LandFirstHits_fz3);
   cbmsim->SetBranchAddress("LandFirstHits.fT3",LandFirstHits_fT3);
   cbmsim->SetBranchAddress("LandFirstHits.fx4",LandFirstHits_fx4);
   cbmsim->SetBranchAddress("LandFirstHits.fy4",LandFirstHits_fy4);
   cbmsim->SetBranchAddress("LandFirstHits.fz4",LandFirstHits_fz4);
   cbmsim->SetBranchAddress("LandFirstHits.fT4",LandFirstHits_fT4);
   cbmsim->SetBranchAddress("LandFirstHits.fx5",LandFirstHits_fx5);
   cbmsim->SetBranchAddress("LandFirstHits.fy5",LandFirstHits_fy5);
   cbmsim->SetBranchAddress("LandFirstHits.fz5",LandFirstHits_fz5);
   cbmsim->SetBranchAddress("LandFirstHits.fT5",LandFirstHits_fT5);
   cbmsim->SetBranchAddress("veto_segPoint",&cbmroot_veto_seg_veto_segPoint_);
   cbmsim->SetBranchAddress("veto_segPoint.fUniqueID",veto_segPoint_fUniqueID);
   cbmsim->SetBranchAddress("veto_segPoint.fBits",veto_segPoint_fBits);
   cbmsim->SetBranchAddress("veto_segPoint.fLink",veto_segPoint_fLink);
   cbmsim->SetBranchAddress("veto_segPoint.fTrackID",veto_segPoint_fTrackID);
   cbmsim->SetBranchAddress("veto_segPoint.fEventId",veto_segPoint_fEventId);
   cbmsim->SetBranchAddress("veto_segPoint.fPx",veto_segPoint_fPx);
   cbmsim->SetBranchAddress("veto_segPoint.fPy",veto_segPoint_fPy);
   cbmsim->SetBranchAddress("veto_segPoint.fPz",veto_segPoint_fPz);
   cbmsim->SetBranchAddress("veto_segPoint.fTime",veto_segPoint_fTime);
   cbmsim->SetBranchAddress("veto_segPoint.fLength",veto_segPoint_fLength);
   cbmsim->SetBranchAddress("veto_segPoint.fELoss",veto_segPoint_fELoss);
   cbmsim->SetBranchAddress("veto_segPoint.fDetectorID",veto_segPoint_fDetectorID);
   cbmsim->SetBranchAddress("veto_segPoint.fX",veto_segPoint_fX);
   cbmsim->SetBranchAddress("veto_segPoint.fY",veto_segPoint_fY);
   cbmsim->SetBranchAddress("veto_segPoint.fZ",veto_segPoint_fZ);
   cbmsim->SetBranchAddress("veto_segPoint.fX_out",veto_segPoint_fX_out);
   cbmsim->SetBranchAddress("veto_segPoint.fY_out",veto_segPoint_fY_out);
   cbmsim->SetBranchAddress("veto_segPoint.fZ_out",veto_segPoint_fZ_out);
   cbmsim->SetBranchAddress("veto_segPoint.fPx_out",veto_segPoint_fPx_out);
   cbmsim->SetBranchAddress("veto_segPoint.fPy_out",veto_segPoint_fPy_out);
   cbmsim->SetBranchAddress("veto_segPoint.fPz_out",veto_segPoint_fPz_out);
   cbmsim->SetBranchAddress("veto_segPoint.fSector",veto_segPoint_fSector);
   cbmsim->SetBranchAddress("veto_segPoint.fPaddleNb",veto_segPoint_fPaddleNb);
   cbmsim->SetBranchAddress("veto_segPoint.fPaddleTyp",veto_segPoint_fPaddleTyp);
   cbmsim->SetBranchAddress("veto_segPoint.fLightYield",veto_segPoint_fLightYield);
   cbmsim->SetBranchAddress("veto_segFirstHits",&cbmroot_veto_seg_veto_segFirstHits_);
   cbmsim->SetBranchAddress("veto_segFirstHits.fUniqueID",veto_segFirstHits_fUniqueID);
   cbmsim->SetBranchAddress("veto_segFirstHits.fBits",veto_segFirstHits_fBits);
   cbmsim->SetBranchAddress("veto_segFirstHits.fx0",veto_segFirstHits_fx0);
   cbmsim->SetBranchAddress("veto_segFirstHits.fy0",veto_segFirstHits_fy0);
   cbmsim->SetBranchAddress("veto_segFirstHits.fz0",veto_segFirstHits_fz0);
   cbmsim->SetBranchAddress("veto_segFirstHits.fT0",veto_segFirstHits_fT0);
   cbmsim->SetBranchAddress("veto_segFirstHits.fx1",veto_segFirstHits_fx1);
   cbmsim->SetBranchAddress("veto_segFirstHits.fy1",veto_segFirstHits_fy1);
   cbmsim->SetBranchAddress("veto_segFirstHits.fz1",veto_segFirstHits_fz1);
   cbmsim->SetBranchAddress("veto_segFirstHits.fT1",veto_segFirstHits_fT1);
   cbmsim->SetBranchAddress("veto_segFirstHits.fx2",veto_segFirstHits_fx2);
   cbmsim->SetBranchAddress("veto_segFirstHits.fy2",veto_segFirstHits_fy2);
   cbmsim->SetBranchAddress("veto_segFirstHits.fz2",veto_segFirstHits_fz2);
   cbmsim->SetBranchAddress("veto_segFirstHits.fT2",veto_segFirstHits_fT2);
   cbmsim->SetBranchAddress("veto_segFirstHits.fx3",veto_segFirstHits_fx3);
   cbmsim->SetBranchAddress("veto_segFirstHits.fy3",veto_segFirstHits_fy3);
   cbmsim->SetBranchAddress("veto_segFirstHits.fz3",veto_segFirstHits_fz3);
   cbmsim->SetBranchAddress("veto_segFirstHits.fT3",veto_segFirstHits_fT3);
   cbmsim->SetBranchAddress("veto_segFirstHits.fx4",veto_segFirstHits_fx4);
   cbmsim->SetBranchAddress("veto_segFirstHits.fy4",veto_segFirstHits_fy4);
   cbmsim->SetBranchAddress("veto_segFirstHits.fz4",veto_segFirstHits_fz4);
   cbmsim->SetBranchAddress("veto_segFirstHits.fT4",veto_segFirstHits_fT4);
   cbmsim->SetBranchAddress("veto_segFirstHits.fx5",veto_segFirstHits_fx5);
   cbmsim->SetBranchAddress("veto_segFirstHits.fy5",veto_segFirstHits_fy5);
   cbmsim->SetBranchAddress("veto_segFirstHits.fz5",veto_segFirstHits_fz5);
   cbmsim->SetBranchAddress("veto_segFirstHits.fT5",veto_segFirstHits_fT5);
   cbmsim->SetBranchAddress("MFIPoint",&cbmroot_Mfi_MFIPoint_);
   cbmsim->SetBranchAddress("MFIPoint.fUniqueID",&MFIPoint_fUniqueID);
   cbmsim->SetBranchAddress("MFIPoint.fBits",&MFIPoint_fBits);
   cbmsim->SetBranchAddress("MFIPoint.fLink",&MFIPoint_fLink);
   cbmsim->SetBranchAddress("MFIPoint.fTrackID",&MFIPoint_fTrackID);
   cbmsim->SetBranchAddress("MFIPoint.fEventId",&MFIPoint_fEventId);
   cbmsim->SetBranchAddress("MFIPoint.fPx",&MFIPoint_fPx);
   cbmsim->SetBranchAddress("MFIPoint.fPy",&MFIPoint_fPy);
   cbmsim->SetBranchAddress("MFIPoint.fPz",&MFIPoint_fPz);
   cbmsim->SetBranchAddress("MFIPoint.fTime",&MFIPoint_fTime);
   cbmsim->SetBranchAddress("MFIPoint.fLength",&MFIPoint_fLength);
   cbmsim->SetBranchAddress("MFIPoint.fELoss",&MFIPoint_fELoss);
   cbmsim->SetBranchAddress("MFIPoint.fDetectorID",&MFIPoint_fDetectorID);
   cbmsim->SetBranchAddress("MFIPoint.fX",&MFIPoint_fX);
   cbmsim->SetBranchAddress("MFIPoint.fY",&MFIPoint_fY);
   cbmsim->SetBranchAddress("MFIPoint.fZ",&MFIPoint_fZ);
   cbmsim->SetBranchAddress("MFIPoint.fX_out",&MFIPoint_fX_out);
   cbmsim->SetBranchAddress("MFIPoint.fY_out",&MFIPoint_fY_out);
   cbmsim->SetBranchAddress("MFIPoint.fZ_out",&MFIPoint_fZ_out);
   cbmsim->SetBranchAddress("MFIPoint.fPx_out",&MFIPoint_fPx_out);
   cbmsim->SetBranchAddress("MFIPoint.fPy_out",&MFIPoint_fPy_out);
   cbmsim->SetBranchAddress("MFIPoint.fPz_out",&MFIPoint_fPz_out);
   cbmsim->SetBranchAddress("MFIPoint.fModule",&MFIPoint_fModule);
   cbmsim->SetBranchAddress("PSPPoint",&cbmroot_Psp_PSPPoint_);
   cbmsim->SetBranchAddress("PSPPoint.fUniqueID",PSPPoint_fUniqueID);
   cbmsim->SetBranchAddress("PSPPoint.fBits",PSPPoint_fBits);
   cbmsim->SetBranchAddress("PSPPoint.fLink",PSPPoint_fLink);
   cbmsim->SetBranchAddress("PSPPoint.fTrackID",PSPPoint_fTrackID);
   cbmsim->SetBranchAddress("PSPPoint.fEventId",PSPPoint_fEventId);
   cbmsim->SetBranchAddress("PSPPoint.fPx",PSPPoint_fPx);
   cbmsim->SetBranchAddress("PSPPoint.fPy",PSPPoint_fPy);
   cbmsim->SetBranchAddress("PSPPoint.fPz",PSPPoint_fPz);
   cbmsim->SetBranchAddress("PSPPoint.fTime",PSPPoint_fTime);
   cbmsim->SetBranchAddress("PSPPoint.fLength",PSPPoint_fLength);
   cbmsim->SetBranchAddress("PSPPoint.fELoss",PSPPoint_fELoss);
   cbmsim->SetBranchAddress("PSPPoint.fDetectorID",PSPPoint_fDetectorID);
   cbmsim->SetBranchAddress("PSPPoint.fX",PSPPoint_fX);
   cbmsim->SetBranchAddress("PSPPoint.fY",PSPPoint_fY);
   cbmsim->SetBranchAddress("PSPPoint.fZ",PSPPoint_fZ);
   cbmsim->SetBranchAddress("PSPPoint.fX_out",PSPPoint_fX_out);
   cbmsim->SetBranchAddress("PSPPoint.fY_out",PSPPoint_fY_out);
   cbmsim->SetBranchAddress("PSPPoint.fZ_out",PSPPoint_fZ_out);
   cbmsim->SetBranchAddress("PSPPoint.fPx_out",PSPPoint_fPx_out);
   cbmsim->SetBranchAddress("PSPPoint.fPy_out",PSPPoint_fPy_out);
   cbmsim->SetBranchAddress("PSPPoint.fPz_out",PSPPoint_fPz_out);
   cbmsim->SetBranchAddress("PSPPoint.fModule",PSPPoint_fModule);
   cbmsim->SetBranchAddress("MCEventHeader.",&cbmroot_Event_MCEventHeader_);
   cbmsim->SetBranchAddress("MCEventHeader.TNamed.fUniqueID",&cbmroot_Event_MCEventHeader_TNamed_fUniqueID);
   cbmsim->SetBranchAddress("MCEventHeader.TNamed.fBits",&cbmroot_Event_MCEventHeader_TNamed_fBits);
   cbmsim->SetBranchAddress("MCEventHeader.TNamed.fName",&cbmroot_Event_MCEventHeader_TNamed_fName);
   cbmsim->SetBranchAddress("MCEventHeader.TNamed.fTitle",&cbmroot_Event_MCEventHeader_TNamed_fTitle);
   cbmsim->SetBranchAddress("MCEventHeader.fRunId",&cbmroot_Event_MCEventHeader_fRunId);
   cbmsim->SetBranchAddress("MCEventHeader.fEventId",&cbmroot_Event_MCEventHeader_fEventId);
   cbmsim->SetBranchAddress("MCEventHeader.fX",&cbmroot_Event_MCEventHeader_fX);
   cbmsim->SetBranchAddress("MCEventHeader.fY",&cbmroot_Event_MCEventHeader_fY);
   cbmsim->SetBranchAddress("MCEventHeader.fZ",&cbmroot_Event_MCEventHeader_fZ);
   cbmsim->SetBranchAddress("MCEventHeader.fT",&cbmroot_Event_MCEventHeader_fT);
   cbmsim->SetBranchAddress("MCEventHeader.fB",&cbmroot_Event_MCEventHeader_fB);
   cbmsim->SetBranchAddress("MCEventHeader.fNPrim",&cbmroot_Event_MCEventHeader_fNPrim);
   cbmsim->SetBranchAddress("MCEventHeader.fIsSet",&cbmroot_Event_MCEventHeader_fIsSet);
   cbmsim->SetBranchAddress("MCEventHeader.fRotX",&cbmroot_Event_MCEventHeader_fRotX);
   cbmsim->SetBranchAddress("MCEventHeader.fRotY",&cbmroot_Event_MCEventHeader_fRotY);
   cbmsim->SetBranchAddress("MCEventHeader.fRotZ",&cbmroot_Event_MCEventHeader_fRotZ);
   cbmsim->SetBranchAddress("GeoTracks",&cbmroot_MCGeoTrack_GeoTracks_);
   cbmsim->SetBranchAddress("GeoTracks.fUniqueID",GeoTracks_fUniqueID);
   cbmsim->SetBranchAddress("GeoTracks.fBits",GeoTracks_fBits);
   cbmsim->SetBranchAddress("GeoTracks.fGeoAtt",GeoTracks_fGeoAtt);
   cbmsim->SetBranchAddress("GeoTracks.fLineColor",GeoTracks_fLineColor);
   cbmsim->SetBranchAddress("GeoTracks.fLineStyle",GeoTracks_fLineStyle);
   cbmsim->SetBranchAddress("GeoTracks.fLineWidth",GeoTracks_fLineWidth);
   cbmsim->SetBranchAddress("GeoTracks.fMarkerColor",GeoTracks_fMarkerColor);
   cbmsim->SetBranchAddress("GeoTracks.fMarkerStyle",GeoTracks_fMarkerStyle);
   cbmsim->SetBranchAddress("GeoTracks.fMarkerSize",GeoTracks_fMarkerSize);
   cbmsim->SetBranchAddress("GeoTracks.fPDG",GeoTracks_fPDG);
   cbmsim->SetBranchAddress("GeoTracks.fId",GeoTracks_fId);
   cbmsim->SetBranchAddress("GeoTracks.fParent",GeoTracks_fParent);
   cbmsim->SetBranchAddress("GeoTracks.fParticle",GeoTracks_fParticle);
   cbmsim->SetBranchAddress("GeoTracks.fTracks",GeoTracks_fTracks);
   cbmsim->SetBranchAddress("GeoTracks.fPointsSize",GeoTracks_fPointsSize);
   cbmsim->SetBranchAddress("GeoTracks.fNpoints",GeoTracks_fNpoints);
   cbmsim->SetBranchAddress("GeoTracks.fPoints",GeoTracks_fPoints);

//     This is the loop skeleton
//       To read only selected branches, Insert statements like:
// cbmsim->SetBranchStatus("*",0);  // disable all branches
// TTreePlayer->SetBranchStatus("branchname",1);  // activate branchname

   Long64_t nentries = cbmsim->GetEntries();

   Long64_t nbytes = 0;
//   for (Long64_t i=0; i<nentries;i++) {
//      nbytes += cbmsim->GetEntry(i);
//   }
}
